# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: MedCode.in
email: nps798@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  這裡應該有一個敘述，但我不知道要打什麼QAQ
baseurl: "" # the subpath of your site, e.g. /blog
lang: "zh_tw"
url: "https://blog.medcode.in" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  nps798
disqus_shortname: "blog-medcode-in"
comments: true

# Build settings
markdown: kramdown
relative_permalinks: false
permalink: /:categories/:title/

# Posts settings
future: true
safe: false
lsi: false
excerpt_separator: "\n\n"


compress_html:
  comments: ["<!-- ", " -->"]
  clippings: all
  endings: all


sass:
  sass_dir: assets/_sass


images: '/assets/images'
